### ISSUE TITLE
chown: changing ownership of '/arkserver/ShooterGame/Saved': Operation not permitted

### ISSUE THREAD

**Issue by bhechinger** [DrPsychick/ark-server-charts#25]
Trying to deploy this into my kubernetes cluster I get this error at pod startup:

```
➜ kubectl -n ark logs ark-test-ark-cluster-theisland-5f87ff7798-dz52k
###########################################################################
# Ark Server -  Sun Jan 29 13:29:48 UTC 2023
###########################################################################
Ensuring correct permissions...
Shared server files in /arkserver...
chown: changing ownership of '/arkserver/ShooterGame/Saved': Operation not permitted
```

I have this in `values.yaml`:
```
persistence:
  enabled: true

  # game files from steam, the largest volume, includes installed mods
  game:
    storageClass: ceph-block
    accessModes:
      - ReadWriteOnce
    size: 30Gi
    mountPath: /arkserver

  # shared cluster files
  cluster:
    storageClass: ceph-block
    accessModes:
      - ReadWriteOnce
    size: 200Mi
    mountPath: /arkserver/ShooterGame/Saved/clusters

  # contains the world save game and configuration files
  # keeping a backup of this is enough to get your server back up
  save:
    volumeMode: Filesystem
    storageClass: ceph-block
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    mountPath: /arkserver/ShooterGame/Saved
```
edit: added the d which is actually there and got lost in the copy/paste.

I have been completely unable to figure out why this is happening or how to fix it. :(

```
➜ helm version                                                   
version.BuildInfo{Version:"v3.11.0", GitCommit:"472c5736ab01133de504a826bd9ee12cbe4e7904", GitTreeState:"clean", GoVersion:"go1.18.10"}
➜ kubectl version --short
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.25.2+k3s1
➜ helm -n ark list                                               
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ark-test        ark             1               2023-01-29 13:24:31.70050347 +0000 UTC  deployed        ark-cluster-0.1.10      latest
```
