### ISSUE TITLE
Change `servers` to be a `dict`

### ISSUE THREAD

**Issue by DrPsychick** [DrPsychick/ark-server-charts#6]
## Problem
referencing servers by number in a list is error prone and not "readable"

```
helm [...] --set servers[0].map="Extinction" [...]
vs.
helm [...] --set servers.extinction.map="Extinction" [...]
```

## Solution
Switch `servers` to be a dict
```
servers:
  extinction:
    map: Extinction
    maxPlayers: 10
```

## Benefit
You can define servers in separate files and pass them all during deployment
```
helm [...] --values server1-values.yaml,server2-values.yaml, ... [...]
```
